/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) multistage_straight_integrator1_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[27] = {23, 1, 0, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* multistage_straight_integrator1_expl_vde_adj:(i0[23],i1[23],i2[0],i3[])->(o0[23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=3.0808157780080393e+01;
  a2=arg[0]? arg[0][6] : 0;
  a3=(a1*a2);
  a4=arg[0]? arg[0][15] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][7] : 0;
  a7=(a1*a6);
  a8=arg[0]? arg[0][16] : 0;
  a9=(a7*a8);
  a5=(a5+a9);
  a9=arg[0]? arg[0][8] : 0;
  a10=(a1*a9);
  a11=arg[0]? arg[0][17] : 0;
  a12=(a10*a11);
  a5=(a5+a12);
  a12=arg[0]? arg[0][19] : 0;
  a13=arg[0]? arg[0][9] : 0;
  a14=arg[0]? arg[0][11] : 0;
  a15=(a13*a14);
  a16=(a12*a15);
  a17=arg[1]? arg[1][14] : 0;
  a16=(a16*a17);
  a18=arg[0]? arg[0][10] : 0;
  a19=(a13*a18);
  a20=(a12*a19);
  a21=arg[1]? arg[1][13] : 0;
  a20=(a20*a21);
  a16=(a16+a20);
  a20=casadi_sq(a14);
  a22=casadi_sq(a18);
  a20=(a20+a22);
  a22=(a12*a20);
  a23=arg[1]? arg[1][12] : 0;
  a22=(a22*a23);
  a16=(a16-a22);
  a22=(a5*a16);
  a24=arg[0]? arg[0][18] : 0;
  a25=(a13*a14);
  a26=(a24*a25);
  a26=(a26*a17);
  a27=(a13*a18);
  a28=(a24*a27);
  a28=(a28*a21);
  a26=(a26+a28);
  a28=casadi_sq(a14);
  a29=casadi_sq(a18);
  a28=(a28+a29);
  a29=(a24*a28);
  a29=(a29*a23);
  a26=(a26-a29);
  a29=(a5*a26);
  a22=(a22+a29);
  a29=arg[1]? arg[1][9] : 0;
  a30=(a5*a29);
  a22=(a22+a30);
  a30=1.3478569028785174e+01;
  a31=(a30*a13);
  a32=(a31*a4);
  a33=(a30*a18);
  a34=(a33*a8);
  a32=(a32+a34);
  a34=(a30*a14);
  a35=(a34*a11);
  a32=(a32+a35);
  a35=arg[1]? arg[1][6] : 0;
  a36=(a32*a35);
  a22=(a22-a36);
  a36=arg[1]? arg[1][8] : 0;
  a37=(a14*a36);
  a38=(a14*a18);
  a39=(a12*a38);
  a39=(a39*a21);
  a40=casadi_sq(a18);
  a41=casadi_sq(a13);
  a40=(a40+a41);
  a41=(a12*a40);
  a41=(a41*a17);
  a39=(a39-a41);
  a41=(a14*a13);
  a42=(a12*a41);
  a42=(a42*a23);
  a39=(a39+a42);
  a42=(a9*a39);
  a43=(a18*a14);
  a44=(a12*a43);
  a44=(a44*a17);
  a45=casadi_sq(a14);
  a46=casadi_sq(a13);
  a45=(a45+a46);
  a46=(a12*a45);
  a46=(a46*a21);
  a44=(a44-a46);
  a46=(a18*a13);
  a47=(a12*a46);
  a47=(a47*a23);
  a44=(a44+a47);
  a47=(a6*a44);
  a42=(a42+a47);
  a47=(a2*a16);
  a42=(a42+a47);
  a47=(a14*a18);
  a48=(a24*a47);
  a48=(a48*a21);
  a49=casadi_sq(a18);
  a50=casadi_sq(a13);
  a49=(a49+a50);
  a50=(a24*a49);
  a50=(a50*a17);
  a48=(a48-a50);
  a50=(a14*a13);
  a51=(a24*a50);
  a51=(a51*a23);
  a48=(a48+a51);
  a51=(a9*a48);
  a42=(a42+a51);
  a51=(a18*a14);
  a52=(a24*a51);
  a52=(a52*a17);
  a53=casadi_sq(a14);
  a54=casadi_sq(a13);
  a53=(a53+a54);
  a54=(a24*a53);
  a54=(a54*a21);
  a52=(a52-a54);
  a54=(a18*a13);
  a55=(a24*a54);
  a55=(a55*a23);
  a52=(a52+a55);
  a55=(a6*a52);
  a42=(a42+a55);
  a55=(a2*a26);
  a42=(a42+a55);
  a55=arg[1]? arg[1][11] : 0;
  a56=(a9*a55);
  a42=(a42+a56);
  a56=arg[1]? arg[1][10] : 0;
  a57=(a6*a56);
  a42=(a42+a57);
  a57=(a2*a29);
  a42=(a42+a57);
  a37=(a37-a42);
  a42=arg[1]? arg[1][7] : 0;
  a57=(a18*a42);
  a37=(a37+a57);
  a57=(a13*a35);
  a37=(a37+a57);
  a57=(a4*a37);
  a57=(a1*a57);
  a22=(a22+a57);
  if (res[0]!=0) res[0][3]=a22;
  a22=(a5*a44);
  a57=(a5*a52);
  a22=(a22+a57);
  a57=(a5*a56);
  a22=(a22+a57);
  a57=(a32*a42);
  a22=(a22-a57);
  a57=(a8*a37);
  a57=(a1*a57);
  a22=(a22+a57);
  if (res[0]!=0) res[0][4]=a22;
  a22=(a5*a39);
  a57=(a5*a48);
  a22=(a22+a57);
  a57=(a5*a55);
  a22=(a22+a57);
  a57=(a32*a36);
  a22=(a22-a57);
  a57=(a11*a37);
  a57=(a1*a57);
  a22=(a22+a57);
  if (res[0]!=0) res[0][5]=a22;
  a22=arg[0]? arg[0][5] : 0;
  a57=(a22*a39);
  a58=arg[0]? arg[0][4] : 0;
  a59=(a58*a44);
  a57=(a57+a59);
  a59=arg[0]? arg[0][3] : 0;
  a60=(a59*a16);
  a57=(a57+a60);
  a60=(a22*a48);
  a57=(a57+a60);
  a60=(a58*a52);
  a57=(a57+a60);
  a60=(a59*a26);
  a57=(a57+a60);
  a60=(a22*a55);
  a57=(a57+a60);
  a60=(a58*a56);
  a57=(a57+a60);
  a60=(a59*a29);
  a57=(a57+a60);
  a60=arg[1]? arg[1][5] : 0;
  a61=(a14*a60);
  a57=(a57-a61);
  a61=arg[1]? arg[1][4] : 0;
  a62=(a18*a61);
  a57=(a57-a62);
  a62=arg[1]? arg[1][3] : 0;
  a63=(a13*a62);
  a57=(a57-a63);
  a63=(a4*a57);
  a63=(a1*a63);
  a64=(a1*a59);
  a65=(a64*a4);
  a66=(a1*a58);
  a67=(a66*a8);
  a65=(a65+a67);
  a67=(a1*a22);
  a68=(a67*a11);
  a65=(a65+a68);
  a16=(a65*a16);
  a26=(a65*a26);
  a16=(a16+a26);
  a29=(a65*a29);
  a16=(a16+a29);
  a63=(a63-a16);
  a16=(a32*a62);
  a63=(a63+a16);
  if (res[0]!=0) res[0][6]=a63;
  a63=(a32*a61);
  a44=(a65*a44);
  a52=(a65*a52);
  a44=(a44+a52);
  a56=(a65*a56);
  a44=(a44+a56);
  a63=(a63-a44);
  a44=(a8*a57);
  a44=(a1*a44);
  a63=(a63+a44);
  if (res[0]!=0) res[0][7]=a63;
  a32=(a32*a60);
  a39=(a65*a39);
  a48=(a65*a48);
  a39=(a39+a48);
  a55=(a65*a55);
  a39=(a39+a55);
  a32=(a32-a39);
  a39=(a11*a57);
  a1=(a1*a39);
  a32=(a32+a1);
  if (res[0]!=0) res[0][8]=a32;
  a32=arg[0]? arg[0][14] : 0;
  a1=arg[1]? arg[1][16] : 0;
  a39=(a32*a1);
  a55=arg[0]? arg[0][13] : 0;
  a48=arg[1]? arg[1][17] : 0;
  a63=(a55*a48);
  a39=(a39-a63);
  a63=(a59*a5);
  a44=(a2*a65);
  a63=(a63-a44);
  a44=(a63*a17);
  a56=(a12*a44);
  a52=(a14*a56);
  a39=(a39+a52);
  a52=(a13+a13);
  a16=(a22*a5);
  a29=(a9*a65);
  a16=(a16-a29);
  a29=(a16*a17);
  a26=(a12*a29);
  a52=(a52*a26);
  a39=(a39-a52);
  a52=(a59*a5);
  a68=(a2*a65);
  a52=(a52-a68);
  a68=(a52*a17);
  a69=(a24*a68);
  a70=(a14*a69);
  a39=(a39+a70);
  a70=(a13+a13);
  a71=(a22*a5);
  a72=(a9*a65);
  a71=(a71-a72);
  a72=(a71*a17);
  a73=(a24*a72);
  a70=(a70*a73);
  a39=(a39-a70);
  a70=(a63*a21);
  a74=(a12*a70);
  a75=(a18*a74);
  a39=(a39+a75);
  a75=(a13+a13);
  a76=(a58*a5);
  a77=(a6*a65);
  a76=(a76-a77);
  a77=(a76*a21);
  a78=(a12*a77);
  a75=(a75*a78);
  a39=(a39-a75);
  a75=(a52*a21);
  a79=(a24*a75);
  a80=(a18*a79);
  a39=(a39+a80);
  a80=(a13+a13);
  a81=(a58*a5);
  a82=(a6*a65);
  a81=(a81-a82);
  a82=(a81*a21);
  a83=(a24*a82);
  a80=(a80*a83);
  a39=(a39-a80);
  a80=(a16*a23);
  a84=(a12*a80);
  a85=(a14*a84);
  a39=(a39+a85);
  a85=(a76*a23);
  a86=(a12*a85);
  a87=(a18*a86);
  a39=(a39+a87);
  a87=(a71*a23);
  a88=(a24*a87);
  a89=(a14*a88);
  a39=(a39+a89);
  a89=(a81*a23);
  a90=(a24*a89);
  a91=(a18*a90);
  a39=(a39+a91);
  a91=(a65*a35);
  a39=(a39+a91);
  a91=(a5*a62);
  a39=(a39-a91);
  a9=(a9*a60);
  a22=(a22*a36);
  a58=(a58*a42);
  a22=(a22+a58);
  a59=(a59*a35);
  a22=(a22+a59);
  a9=(a9-a22);
  a6=(a6*a61);
  a9=(a9+a6);
  a2=(a2*a62);
  a9=(a9+a2);
  a4=(a4*a9);
  a4=(a30*a4);
  a39=(a39+a4);
  a4=arg[1]? arg[1][0] : 0;
  a39=(a39+a4);
  if (res[0]!=0) res[0][9]=a39;
  a39=arg[0]? arg[0][12] : 0;
  a4=(a39*a48);
  a2=arg[1]? arg[1][15] : 0;
  a32=(a32*a2);
  a4=(a4-a32);
  a76=(a76*a17);
  a32=(a12*a76);
  a62=(a14*a32);
  a4=(a4+a62);
  a62=(a18+a18);
  a62=(a62*a26);
  a4=(a4-a62);
  a81=(a81*a17);
  a17=(a24*a81);
  a62=(a14*a17);
  a4=(a4+a62);
  a62=(a18+a18);
  a62=(a62*a73);
  a4=(a4-a62);
  a16=(a16*a21);
  a62=(a12*a16);
  a73=(a14*a62);
  a4=(a4+a73);
  a74=(a13*a74);
  a4=(a4+a74);
  a71=(a71*a21);
  a21=(a24*a71);
  a74=(a14*a21);
  a4=(a4+a74);
  a79=(a13*a79);
  a4=(a4+a79);
  a86=(a13*a86);
  a4=(a4+a86);
  a86=(a18+a18);
  a63=(a63*a23);
  a12=(a12*a63);
  a86=(a86*a12);
  a4=(a4-a86);
  a90=(a13*a90);
  a4=(a4+a90);
  a90=(a18+a18);
  a52=(a52*a23);
  a24=(a24*a52);
  a90=(a90*a24);
  a4=(a4-a90);
  a42=(a65*a42);
  a4=(a4+a42);
  a61=(a5*a61);
  a4=(a4-a61);
  a8=(a8*a9);
  a8=(a30*a8);
  a4=(a4+a8);
  a8=arg[1]? arg[1][1] : 0;
  a4=(a4+a8);
  if (res[0]!=0) res[0][10]=a4;
  a55=(a55*a2);
  a39=(a39*a1);
  a55=(a55-a39);
  a32=(a18*a32);
  a55=(a55+a32);
  a56=(a13*a56);
  a55=(a55+a56);
  a17=(a18*a17);
  a55=(a55+a17);
  a69=(a13*a69);
  a55=(a55+a69);
  a62=(a18*a62);
  a55=(a55+a62);
  a62=(a14+a14);
  a62=(a62*a78);
  a55=(a55-a62);
  a21=(a18*a21);
  a55=(a55+a21);
  a21=(a14+a14);
  a21=(a21*a83);
  a55=(a55-a21);
  a84=(a13*a84);
  a55=(a55+a84);
  a84=(a14+a14);
  a84=(a84*a12);
  a55=(a55-a84);
  a88=(a13*a88);
  a55=(a55+a88);
  a88=(a14+a14);
  a88=(a88*a24);
  a55=(a55-a88);
  a65=(a65*a36);
  a55=(a55+a65);
  a5=(a5*a60);
  a55=(a55-a5);
  a11=(a11*a9);
  a30=(a30*a11);
  a55=(a55+a30);
  a30=arg[1]? arg[1][2] : 0;
  a55=(a55+a30);
  if (res[0]!=0) res[0][11]=a55;
  a55=(a18*a48);
  a30=(a14*a1);
  a55=(a55-a30);
  if (res[0]!=0) res[0][12]=a55;
  a14=(a14*a2);
  a48=(a13*a48);
  a14=(a14-a48);
  if (res[0]!=0) res[0][13]=a14;
  a13=(a13*a1);
  a18=(a18*a2);
  a13=(a13-a18);
  if (res[0]!=0) res[0][14]=a13;
  a64=(a64*a37);
  a3=(a3*a57);
  a64=(a64+a3);
  a31=(a31*a9);
  a64=(a64+a31);
  if (res[0]!=0) res[0][15]=a64;
  a66=(a66*a37);
  a7=(a7*a57);
  a66=(a66+a7);
  a33=(a33*a9);
  a66=(a66+a33);
  if (res[0]!=0) res[0][16]=a66;
  a67=(a67*a37);
  a10=(a10*a57);
  a67=(a67+a10);
  a34=(a34*a9);
  a67=(a67+a34);
  if (res[0]!=0) res[0][17]=a67;
  a51=(a51*a81);
  a25=(a25*a68);
  a51=(a51+a25);
  a49=(a49*a72);
  a51=(a51-a49);
  a47=(a47*a71);
  a51=(a51+a47);
  a27=(a27*a75);
  a51=(a51+a27);
  a53=(a53*a82);
  a51=(a51-a53);
  a50=(a50*a87);
  a51=(a51+a50);
  a54=(a54*a89);
  a51=(a51+a54);
  a28=(a28*a52);
  a51=(a51-a28);
  if (res[0]!=0) res[0][18]=a51;
  a43=(a43*a76);
  a15=(a15*a44);
  a43=(a43+a15);
  a40=(a40*a29);
  a43=(a43-a40);
  a38=(a38*a16);
  a43=(a43+a38);
  a19=(a19*a70);
  a43=(a43+a19);
  a45=(a45*a77);
  a43=(a43-a45);
  a41=(a41*a80);
  a43=(a43+a41);
  a46=(a46*a85);
  a43=(a43+a46);
  a20=(a20*a63);
  a43=(a43-a20);
  if (res[0]!=0) res[0][19]=a43;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int multistage_straight_integrator1_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int multistage_straight_integrator1_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int multistage_straight_integrator1_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multistage_straight_integrator1_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int multistage_straight_integrator1_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multistage_straight_integrator1_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void multistage_straight_integrator1_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void multistage_straight_integrator1_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int multistage_straight_integrator1_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int multistage_straight_integrator1_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real multistage_straight_integrator1_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multistage_straight_integrator1_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multistage_straight_integrator1_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multistage_straight_integrator1_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multistage_straight_integrator1_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int multistage_straight_integrator1_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
